### ISSUE TITLE
Site crashes if you sign in and then click clear saved progress

### ISSUE THREAD

**Issue by SamSamskies** [saving-satoshi/saving-satoshi#114]
**To Reproduce**

1. Open site in incognito window
2. Click on avatar icon on top right
3. Click `I've copied and backed up my code`
4. Click on avatar icon on top right again
5. Click `Clear saved progress`

**Screenshots and/or logs**

https://user-images.githubusercontent.com/3655410/215148827-2846c821-a101-48cf-b635-72f9732329cb.mp4

**Comment by SamSamskies** [comment]
Cause seems to be a similar issue to https://github.com/saving-satoshi/saving-satoshi/issues/94.

Took a quick glance at the code and based on [the previous discussion ](https://github.com/saving-satoshi/saving-satoshi/pull/96), I think the `LoginModal` should only be rendered in `NavBar` if the user is registered. I also noticed a bunch of redundant code for keeping track of user state. Might be worth it to consolidate the user state management into a provider or hook.

**Comment by GBKS** [comment]
Yes, looks like state management across the signup/login modals is broken. For step 5, you currently see the login state of the login modal, but you are already logged in and should see that state.

I think the problem is that the two modals do not refresh when they become visible. So they are dealing with an outdated state. We may need to introduce some type of global event bus to broadcast log-in/log-out/user-update states, or find a way to introduce a globally accessible reactive user object whose properties update components. I am not super well-versed with React and Next, maybe you have some good ideas on how to achieve this?

**Comment by SamSamskies** [comment]
Maybe use something like `use-local-storage-state` hook https://github.com/astoilkov/use-local-storage-state. That looks like it broadcasts events whenever the values in localstorage are updated. It might not be necessary though. It might be possible to just use React Context or a simple custom `useUserReducer` hook to handle the user state management.

**Comment by SamSamskies** [comment]
If not one else wants to tackle this, I can jump on it.

**Comment by GBKS** [comment]
Please go ahead. Would be amazing if you can solve this.

**Comment by SamSamskies** [comment]
@ecurrencyhodler you can assign this to me and move it to in progress.
