### ISSUE TITLE
ch 10 - user solutions do not persist

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1182]
One thing I've noticed while QA'ing chapter 10 is if I go back to an exercise I've already completed, my solution (the output amounts and scripts) are not persisted. 

To reproduce, revisit a chapter 10 exercise you have previously completed.

**Comment by benalleng** [comment]
seeing as we have all the previous "correct states" i guess my question is why would they want to go back to see an old solution versus changing tabs?

**Comment by satsie** [comment]
Oh whoa, I didn't realize that. I was flipping back to old challenges to look at and copy my script answers. This is somewhat related to Matthew's request, https://github.com/saving-satoshi/saving-satoshi/issues/1138. If we do that ticket, would we get this issue fixed for free? We've trained the user that they can go back and look at their previous solutions. While it turns out we do indeed save the user's solution to a previous exercise, it isn't in the same spot as it is for previous chapters (aka the page for the previous challenge). I personally would like to see this fixed (not high priority), but respect if I'm in the minority here.

**Comment by benalleng** [comment]
So this is a little more complicated as we would have to add the save load feature for these challenges. as we fix #1138 we would still have to create some conditional to override what is the normal default as the user's code. instead of the challenge default. I think it would be best to start with adding some copy early on to show the user that they can switch tabs to previous states and fixing #1138 and if it still feels like thats not sufficient we can look into adding the save-load for this chapter

**Comment by benalleng** [comment]
So i think from Carla's feedback it does seem like the standard user flow is to want to copy these scripts.

**Comment by satsie** [comment]
I see, and I agree. I think we should first start by fixing #1138. If that's not enough, then add the copy. 

When I filed this issue I didn't realize I was was looking for the same thing several other testers have since mentioned: to be able to copy and make edits to my previous answer so I can submit it as solution to the current challenge. 

Just the thought of having to do that conditional you mention that would override the challenge default with the user code is enough to make me close this issue as a "won't fix" :laughing:
