### ISSUE TITLE
Progress indicators on top right are not properly being updated anymore

### ISSUE THREAD

**Issue by SamSamskies** [saving-satoshi/saving-satoshi#123]
**Describe the bug**
After completing the first exercise, the number one block used to update to have a checkmark and the lock would disappear on block two.

before:
![Screenshot 2023-02-01 at 12 26 50 PM](https://user-images.githubusercontent.com/3655410/216131308-65a24d22-875d-4ed1-8f21-5dcd56d3a730.png)

now:
![Screenshot 2023-02-01 at 12 31 13 PM](https://user-images.githubusercontent.com/3655410/216131342-101f1840-9cb7-4b6d-ad9c-b2dd8e21d616.png)

I think this bug was introduced in [the big refactor](https://github.com/saving-satoshi/saving-satoshi/pull/118).

The value in localStorage correctly reflects that the user is on the 2nd lesson, but the UI is not updating as expected.

**To Reproduce**
You can check previous behavior here https://saving-satoshi-git-fork-1t1e1-ss102navbar-088171-saving-satoshi.vercel.app/ and compare that to what is currently deployed https://savingsatoshi.com/.

**Comment by SamSamskies** [comment]
I've noticed bugs get fixed and then new ones pop up constantly. Probably a sign that some basic e2e tests are needed.

**Comment by afterburn** [comment]
I think this bug was introduced by the changes I've made to our routing. We currently only get the users progress when certain components render (`components/Navbar/Tab.tsx` in this case) using our new `useStatus` hook. The problem I think is that when the user completes `genesis-2` we save the new progress state to localStorage after a delay, but the `useStatus` hook in the Tab component never executes again until you navigate to a new page.

If you ask me a better approach for all this is to use React Context that has some 'progress' state which gets initialized with data from localStorage (if it exists) when the app mounts, and gets updated when you complete a lesson/chapter. This will ensure that components depending on that progress state will automatically rerender, which is currently not the case. I think this is a better approach than relying on navigation.

I'm happy to resolve this issue somewhere this week, unless you want to take it @SamSamskies? You already have a PR open for [user state management](https://github.com/saving-satoshi/saving-satoshi/pull/119) so perhaps this is something you'd like to pick up as well?

**Comment by SamSamskies** [comment]
I can take a look at it tomorrow. It's possibly an easy fix with the changes I made on my PR to fix the user state management. If it's not an easy fix, I'll punt it over to you. 😂

**Comment by afterburn** [comment]
Sounds good, thanks!

**Comment by SamSamskies** [comment]
fixed by https://github.com/saving-satoshi/saving-satoshi/pull/119
