### ISSUE TITLE
Revise the about page copy

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#175]
Don't think the information is really accurate anymore. Things to consider:

- Is the story intro still accurate?
- Let's describe the demo state, what's included and what to expect going forward
- Let's expand on "How to contribute". Just opening an issue is fine for small bugs, but not helpful if someone wants to help with design, localization, story, etc
- Update list of contributors
- Include a simple way to give feedback on the learning experience

What else?

I suggest starting a Google doc for drafting up a new and improved version of this page.

**Comment by ecurrencyhodler** [comment]
I can take a first stab at this.

**Comment by ecurrencyhodler** [comment]
Okay so the story is still being ironed out. I suggest we keep the plot we have for the demo. I've revised the copy a little bit in the about section though.

I provided a short description of where we're at with the demo but left the future state open.

It'd be great if we could divide the story section from the rest of the page with a divider of some sort. When I first came across the project, I was confused because I didn't realize I was essentially reading a section that was no longer tied to the story.

For the contribution portion, I think the best place is to direct them to join us in slack.

Here's the rough draft:
https://docs.google.com/document/d/1elcvdj88LkJ2nP7sB1HlHy8UE2ESrZ1g4DgEgwbD9zw/edit?usp=sharing

**Comment by GBKS** [comment]
Thanks for starting this. I made some changes and left a few comments.

**Comment by adamjonas** [comment]
ACK on the doc modulo the comments I left

**Comment by adamjonas** [comment]
We need to design a form? Can't we start with a simple google form to start?

**Comment by ecurrencyhodler** [comment]
No the about page as a whole needs to be designed with the divider. I'm also not sure if he wanted to change the lay out in a different way. 

But yes we can definitely use a google form to start.

**Comment by ecurrencyhodler** [comment]
Here's the google form for review: https://forms.gle/WhdJwcKKetB9sFL79

**Comment by afterburn** [comment]
@ecurrencyhodler is this issue ready for dev now? thanks

**Comment by ecurrencyhodler** [comment]
Not yet. Still waiting for design. I'm not sure Christoph wants to redesign the about page or if changing the copy is enough.

**Comment by GBKS** [comment]
Thanks for the updated copy, I prepped Figma mock-ups [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A26542&t=B0b3qToHvkRzFrti-1). All I did was update the copy and insert a few dividers, as I don't think a big redesign of this page is important for the demo.

If we make the "Feedback" header in this page a linkable element, we can send people here whenever we want to give them an option for provide feedback (like the end of chapter 1).

**Comment by GBKS** [comment]
@ecurrencyhodler I took a look at the form and have some feedback. What's the best way to provide it?

Overall, I think we should start a bit more approachable and top-level:
- "Give us feedback" is a bit pushy. How about "How was your learning experience?" or "How did you like Saving Satoshi so far?"
- How about adding a "How would you describe Saving Satoshi?" question to get an understanding of whether they are on the same page as we are on what this is about
- Would also be got to know their prior familiarity with bitcoin (in general, and as related to building on it).
- We may want to split out feedback on the learning experience, story, and website so we can better evaluate where exactly the weak/strong points are
- Let's add a thank you note above the Submit button to let them know again that we appreciate their input.

What the does the screen look like when you submit the form? Do we take users back to the site?

**Comment by ecurrencyhodler** [comment]
@GBKS best place is to do it [here](https://docs.google.com/document/d/10uECK5RWey0cEuuHO_zlNo0lJOR0To8kC4uVUAV2nXc/edit).

But I'll incorporate your comments too.

**Comment by adamjonas** [comment]
Unsolicited 2¢ on the form - I think we should be mindful of asking people to fill out a long form for a short demo and really push to have a purpose behind all the questions we are asking and the ease of answering them. It will help increase our response rate and leave them with an overall positive feeling because this survey _is_ part of the Saving Satoshi experience.

**Comment by ecurrencyhodler** [comment]
For the feedback form, I made suggestions to remove some questions. Also made a suggestion for the post-submission message.

**Comment by ecurrencyhodler** [comment]
Also @afterburn not sure if you started on this one yet. But we need to really quickly update the copy in the about page to reflect the new story. I left a comment in figma.

**Comment by afterburn** [comment]
Nope I haven't started on this yet, I'll assign it to myself. Please comment here if copy is ready, and it would be greatly appreciated if you can provide a link to the final copy.

**Comment by ecurrencyhodler** [comment]
@afterburn this is g2g. Here's a [link to the final design.](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A26542&t=w7eGLP1jvD78Iu8J-1)

**Comment by afterburn** [comment]
Thanks sir @ecurrencyhodler
