### ISSUE TITLE
Add support for a tags in tooltips & modify copy

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#179]
The tool tip text should briefly explain what a block explorer is, and link out to a definition of the term (instead of a block explorer directly). The external link should open in a new window. This is on the [chapter 1, challenge 1 page](https://savingsatoshi.com/en/chapters/chapter-1/genesis-1).

![image](https://user-images.githubusercontent.com/695901/220905125-ac4ce775-41ee-4447-808d-ed048097037d.png)

**Comment by ecurrencyhodler** [comment]
There are two items in this issue:
- [ ] Update tool tip
- [ ] The button should only stretch the full width on mobile. On desktop, it should hug its content (with appropriate padding) (same goes for the button in the [transacting challenge](https://savingsatoshi.com/en/chapters/chapter-1/transacting-2)).

**Comment by afterburn** [comment]
Assigning this to myself just like #182 because our current translation system only allows for the tooltip target itself to be a link, so the words "block explorer" in this case. If we want a link inside of the tooltip window, we need some changes to the translation system, which I don't think is a good first issue 😁.

**Comment by ecurrencyhodler** [comment]
Thanks for taking this kevin!

**Comment by afterburn** [comment]
Moving the second part of this issue (about the button width) to a new one.
