### ISSUE TITLE
Paste is not working on iOS mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#188]
**Describe the bug**
I copied the values for challenge 1. I went to the code section to paste it but the paste option did not appear. Also when I click "paste" the screen refreshed or flashes for some reason.

**To Reproduce**

1. Go to challenge 1 and copy the terminal input
2. Go to "code" and try to copy paste
3. The ability to paste doesn't appear.

**Expected behavior**
Option to paste text should appear.

**Screenshots and/or logs**

https://user-images.githubusercontent.com/32662508/220992645-7f976f00-e65d-4c69-8068-f471d984adb3.MP4

**Comment by vinayaksh42** [comment]
I also noticed this bug when I was trying out the game on safari (mobile). The reason behind this issue is the `react-terminal-ui` that is being used for providing a terminal-like experience. 

Basically, the input area for the terminal is hidden and located at the top-left corner of the web page (https://github.com/jonmbake/react-terminal-ui/blob/master/src/style.css#L108). 

<img width="915" alt="Screenshot 2023-02-26 at 4 25 49 AM" src="https://user-images.githubusercontent.com/54861487/221383358-1a6b2cc7-1203-496b-8136-3e8486c2fbf0.png">

The following issues: https://github.com/saving-satoshi/saving-satoshi/issues/188, https://github.com/saving-satoshi/saving-satoshi/issues/187, https://github.com/saving-satoshi/saving-satoshi/issues/165, and https://github.com/saving-satoshi/saving-satoshi/issues/145 will require us to rework the way we have implemented the terminal UI

**Comment by ecurrencyhodler** [comment]
Wow. Great catch and thanks for categorizing the other issues. Let's dive into this on our call tuesday.

**Comment by ecurrencyhodler** [comment]
Following up here. Here's what kevin had to say.

"I Vinayak's PR is a great first step for building our own terminal. I feel that while third-party libraries will help us build something quickly, sooner or later we're going to need some custom functionality. Sometimes third-party libs have great support for extending the feature set, but most do not. Given that we're not yet sure what the final feature set will be, I think the best approach is to continue with what vinayak has built so far, at least for the time being."

So let's move forward with your PR and we can close out this issue.
