### ISSUE TITLE
Remove /en ending for website

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#189]
**Describe the enhancement**
We should remove the /en in our url: https://savingsatoshi.com/en

**Additional information**
We don't currently support another language at this time.

**Comment by afterburn** [comment]
This is not very easy to do. We could spend time implementing our own fix for this, but I suggest we keep using `/en` until the official i18n solution for Next 13 is out of beta. I definitely don't think this is important for the demo.

**Comment by ecurrencyhodler** [comment]
@adamjonas How do you feel about punting this to a later date?

**Comment by afterburn** [comment]
I think the first mistake was using Next 13 (which is still in beta) with the app directory approach. This has caused some headaches with the translation system in particular, but I feel we've gotten the system to a point now where its workable for a while.

I actually spoke with someone from the Next.js team and they haven't let anything on about whether or not they are even considering addressing the i18n issues some have mentioned. I'm assuming they will though because it doesnt work very well in its current state. So to answer your question about when it's coming out of beta, I have no clue.

I think I can take a stab at making 'en' the default locale so that if its not present in the url it defaults to 'en' anyway. I think that could work.

**Comment by benalleng** [comment]
@afterburn I can go ahead and add that default localization to my PR #169

**Comment by afterburn** [comment]
> @afterburn I can go ahead and add that default localization to my PR #169 

Hey @benalleng , sure thanks. You will have to make some changes in `middleware.ts`, that's where we redirect the user to `/<locale>`. Presumably you'll also have to modify `lib/translate.ts` so it defaults to `en` if no lang param is passed.

**Comment by afterburn** [comment]
Sorry @benalleng I forgot to mention this in my previous comment, since we're using Next 13's app directory approach you might have some difficulty getting the correct page to show up when navigating to `/` since the index page is now under `app/[lang]/page.tsx` as opposed to `/app/page.tsx`. I found the Next 13 docs very lacking on how this should be solved idiomatically within the framework so feel free to do something you think makes sense (and is easiest).

**Comment by adamjonas** [comment]
@ecurrencyhodler 
It really bothers me but shouldn't stand in the way of forward progress or be a blocker of the demo milestone.

**Comment by ecurrencyhodler** [comment]
Briefly sync'd with Ben. It seems like the path to fix this is a bit unclear. I think it's best for us to go through the "to do" list first on our project board and then circle back. So I'm marking this for v1.

**Comment by ecurrencyhodler** [comment]
@benalleng attempted to work on this issue. He achieved some success but also encountered a lot of problems too. When we decide to tackle that PR further he has some code to look at [here](https://github.com/benalleng/saving-satoshi/tree/translationPathname).

**Comment by ecurrencyhodler** [comment]
Discussed this on the call today. We are going to move the home page into its own separate folder to preserve the savingsatoshi.com url. However, the url will contain /en when people hop into other areas of the site. We will shoot for this for the demo.
