### ISSUE TITLE
Replace back button with home button that redirects to challenge page

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#206]
Related to https://github.com/saving-satoshi/saving-satoshi/issues/66#issuecomment-1448280976.

Let's repurpose the back button to a home button that leads to the chapters overview page. The user can still go backwards and forwards in the lesson content using the browser UI back/forwards, and the numerical lesson buttons in the nav bar.

@GBKS will create a mock up for us to implement. Once he does, we'll move this "To Do" for eng to pick it up.

**Comment by ecurrencyhodler** [comment]
Assigning this to christoph for a design.

**Comment by ecurrencyhodler** [comment]
@gadabra is going to move forward with addressing this issue. When we get a logo to replace the back button, we can submit a separate PR to update it.

**Comment by GBKS** [comment]
How about a "power off" icon? Like you're the protagonist in the story and shutting down your computer/terminal. The native browser tooltip would show "Back to all chapters".

![image](https://user-images.githubusercontent.com/695901/223083222-f2d9205b-7e82-4e8c-aab1-d9f399536127.png)

We don't have a good logo that we can simplify and show at a small scale, so that's not a good route at the moment.
