### ISSUE TITLE
Text entered into terminal does not wrap around

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#226]
**Describe the bug**
When I type code into the terminal, the text doesn't wrap. Instead the view scrolls.

But after I complete the challenge, the text wraps. 

**To Reproduce**

1. Go to Challenge 2 pt. 2
2. Type in text
3. See text scroll to the right
4. Hit enter and see text wrap around

**Expected behavior**
The text should wrap around.

**Screenshots and/or logs**
Text scrolls.
<img width="1162" alt="scroll" src="https://user-images.githubusercontent.com/32662508/222787067-320b2824-115a-4336-8aac-f0afc92a61b7.png">
Text is wrapped after completing the challenge.
<img width="1207" alt="wrap" src="https://user-images.githubusercontent.com/32662508/222787119-a14025d9-e6ac-40a6-a6b4-c82ac5282bb9.png">

**Comment by vinayaksh42** [comment]
I made an attempt to solve this issue in my `terminal UI` PR. Earlier it was able to wrap around because the package that we were using was displaying the text in a `div` instead of in an `input` field or `textarea`. If we implement something similar to the package approach we will lose the ability to edit the text or paste text in mobile view. `textarea` might work but it will require a hacky solution as we will have to define the number of rows we want to display for the `textarea` depending on text input.

I will try to implement the `textarea` solution, if anyone knows a better approach then please let me know.
