### ISSUE TITLE
Add a second page to the chapter 1 intro

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#259]
This page goes after [this one](https://savingsatoshi.com/en/chapters/chapter-1) and then leads into the first challenge. The copy in Figma ([here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2374%3A25234&t=1WVTKCVc1kPVBDfc-1)) should be up-to-date (just checked it). An export-ready image can be found [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A25490&t=1WVTKCVc1kPVBDfc-1) (select the image layer and press export in the bottom of the right sidebar).

![image](https://user-images.githubusercontent.com/695901/223947904-b719aaf4-8073-4e4e-bd1f-652d195ab00f.png)

**Comment by vinayaksh42** [comment]
I would like to work on this issue, It might be a little tricky to add this because the introductions are displayed with the URL - `/chapters/chapter-1`, and if we add a dynamic folder named `[intro]` in the `chapters/[slug]` folder it interferes with the `[lesson]` folder as we can't have two dynamic folders under a single folder. One of the possible works around this issue can be modifying the `introduction.tsx` template to sequentially display the two different intros.

**Comment by vinayaksh42** [comment]
> @vinayaksh42 is it possible to treat this page as genesis-1 similarly to how transacting-1 is this intro [page](https://savingsatoshi.com/en/chapters/chapter-1/transacting-1)?

Yes, we can do that but it will require a few modifications to the template for Introduction

**Comment by benalleng** [comment]
Maybe it could be Intro-1 and Intro-2? i guess it all dependes on what we want the Navbar to display 
![image](https://user-images.githubusercontent.com/108441023/224387491-cd97c8c2-e1cd-43c2-a9be-1b06016b0b04.png)
or
![image](https://user-images.githubusercontent.com/108441023/224387551-b9715beb-a544-4c84-98e3-58f6468e583d.png)
