### ISSUE TITLE
Chapter1, Challenge2, Transacting

### ISSUE THREAD

**Issue by sabakhilji** [saving-satoshi/saving-satoshi#310]
For mobile users, it is difficult to copy scriptPubKeyBytes and code to the terminal simultaneously.

![satoshi](https://user-images.githubusercontent.com/52318459/225360331-31f81cb6-f65e-440d-9c64-2ba1329e6f23.png)

I am not sure about it why is it kept like this.
But for mobile users, it is quite difficult to do.

One of the solutions to this problem could be to pass the challenge without asking for scriptPubKeyBytes just as in the previous challenge. Just copy and paste the command.

@GBKS @satsie

**Comment by ecurrencyhodler** [comment]
Saba. Would it be possible to ask you to screen record what you're doing and drink a link to it?  I'd love to see how you're going through the challenge.

**Comment by satsie** [comment]
I agree that this is probably tricky. I've never been a strong believer that coding challenges can translate well to mobile but I want to be proven wrong! Deferring to Christoph on any ways we might be able to improve the flow.

@ecurrencyhodler I think what Saba is doing is copying `echo $scriptPubKeyBytes | xxd -r -p`, and then trying to highlight and replace $scriptPubKeyBytes with `5361746f7368693433335061726b53744368696e6f43413933323433`. One suggestion to smooth this out is removing the copy/paste from the `echo` command, so the user ends up:
1. Typing `echo`
2. pasting in `5361746f7368693433335061726b53744368696e6f43413933323433`
3. finishing up the command by typing ` | xxd -r -p`

**Comment by sabakhilji** [comment]
Hey, correct @satsie. Thanks for making things clear here. I am trying to do the same thing. 
Your suggested solution will make the user journey easy I guess.

**Comment by ecurrencyhodler** [comment]
Hmm that's interesting. I went to type it out, $scriptPubKeyBytes, and then filled out the rest. 

But I can see why someone would copy/paste it. One solution could be to just remove the copy section and instruct people to type it out?

Side note: What if instead of "code" in the mobile view, what do you think about us calling it "terminal"?

**Comment by sabakhilji** [comment]
I think lazy people like me, who don't want to type faces problem with this :).

**Comment by GBKS** [comment]
Then you won't make it very far into this experience, as you'll need to write full scripts just a few further challenges down he line. It is a learning experience, and users will need to do a bit of thinking and typing and learn some pretty complex concepts. There's no way around this, best we can do is to ease users into the complexity little by little and provide support when needed.

**Comment by shaavan** [comment]
I agree with @satsie and @ecurrencyhodler suggestion of removing the copy action from the code on this challenge.

On top of this, I would like to add one more suggestion.

When the user writes `echo $scriptPubKeyBytes | xxd -r -p` instead of the decoded version of `$scriptPubKeyBytes`, they get the following message. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/85434418/225646587-bb9a1091-b1c7-4c39-9c0f-1c80ae53beb7.png">

This provides a strong clue to the user on what to do. However, no such visual hint is present before writing the command.

If we remove copy capability, we should add an extra statement that the variable is not defined for you. Otherwise, it can be annoying for users to manually type `echo $scriptPubKeyBytes | xxd -r -p`, and then realize the challenge wants an expanded version and need to type again (especially for the mobile user).

**Comment by ecurrencyhodler** [comment]
Seems like we're all the same page on removing copy/paste. Christoph made a design update in https://github.com/saving-satoshi/saving-satoshi/issues/310

Going to close this issue as it addresses the same issue.

Thanks for raising it Saba!
