### ISSUE TITLE
Preview image still only visible on /[lang] url

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#312]
I noticed when posting a link to my friends to test the demo that the preview url is still only visible on the `/[lang]` url but looking at the app folder i could not see immediately why this was the case.
@vinayaksh42 any ideas? I know you helped in removing the `/[lang]` url on the homepage and hoped you might have some insight
nothing in `/app/head.tsx` mentions the /[lang] url

**Comment by vinayaksh42** [comment]
The logic for removing the `/en` ending was to simply stop the redirect that was occurring due to `middleware.ts` when a URL without a locale was requested. More info at https://github.com/saving-satoshi/saving-satoshi/pull/247/files#diff-3c67eb27b539c61276d7c7cbcdbe15d4b37a6cbf58bf8bc12c1c4d7619c96d1c

Not sure why this issue might be occurring as in the root folder of `app` we have the actual homepage (https://github.com/saving-satoshi/saving-satoshi/tree/master/app)

**Comment by ecurrencyhodler** [comment]
This preview image is still only available with /[lang] url. Ben/Kevin will investigate this further.
