### ISSUE TITLE
Add help button and link to form

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#343]
Let's add a help button on the top right of the screen like we had in previous designs. When a player clicks on the button, a separate tab opens and they're directed to [this google form](https://forms.gle/NVcg9ukPvUBYjw1u7). This will help us keep tabs on where people are getting stuck.

This feature request was born out of feedback we received during the demo where sometimes people would get stuck in the middle of the chapter but didn't know where to submit feedback about it.

**Comment by GBKS** [comment]
This is now added to all the screens in Figma.

![image](https://user-images.githubusercontent.com/695901/229336917-a02ccb77-6887-4786-9cbe-9f80423f35fe.png)

**Comment by benalleng** [comment]
As an aside I do think that the feedback form used here should be nearly the same as the standard feedback form, just changed to ask where the user got stuck

**Comment by mouxdesign** [comment]
Always a good idea to allow users to contact you in some way if they run into an issue. 

I am just wondering how users will perceive that question mark:

Because then there could be 2 categories:
- People reporting bugs/issues
- People asking for help because they cannot solve the challenge

And then the feedback form or the channel they are directed to would be to collect that form of feedback. 

Or would this to be to collect feedback to understand which challenges were very difficult for people to solve? So collecting info on which challenges can be tweaked and modified?

**Comment by ecurrencyhodler** [comment]
Hey @mouxdesign. I think the primary purpose was to see when someone gets stuck. 

I'm not sure how people will perceive the ? either. It seems like the expectation would be a help page.
