### ISSUE TITLE
User Progress reset upon completion of previous lesson

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#344]
I discovered a potential issue where if a user has completed all the lessons in chapter 1 and decides to redo the Genesis lesson, their user progress gets reset to Chapter 1, Lesson 1. I believe this should not occur. redoing an old lesson should not change the userProgress.

for example:
userProgress after completing all the chapter-1 lessons is `chapter-2, scripting-1` and then the user decides to redo genesis lesson, the userProgress will change to `chapter-1, genesis-1`. 

As discussed on the call to save userProgress on a per-page basis, maybe we can resolve this bug in our backend.

**Comment by ecurrencyhodler** [comment]
Agreed. This shouldn't be addressed via local storage. @afterburn will our new backend account system automatically address this issue? If so we can close it out.

**Comment by afterburn** [comment]
Well it hasn't been built yet but our Progress Saving system on the backend should be smart enough to understand when something is progress and when it isn't. So if a user is on chapter 2 but a `save_progress` call comes in for ch1 genesis it should understand that that isn't progress and ignore the call. This same logic should be present on the frontend though because ideally we shouldn't even send a `save_progress` call if the FE detects is for a chapter/lesson the user has already completed.

This is one of the reasons why I think we should move to having unique codes for each lesson as described [here](https://github.com/saving-satoshi/saving-satoshi-backend/issues/6), that way we can implement the logic needed to understand what lesson code comes after another, and by extension know what is progress and what isn't. 

Concretely this issue is blocked by [this issue](https://github.com/saving-satoshi/saving-satoshi-backend/issues/6).

**Comment by ecurrencyhodler** [comment]
Update from Kevin: After the progress system has been built on the BE we still need to make some modifications to the FE for which I have created https://github.com/saving-satoshi/saving-satoshi/issues/158 and https://github.com/saving-satoshi/saving-satoshi/issues/139. 

Closing this issue.
