### ISSUE TITLE
Snackbar instead of a permanent text area

### ISSUE THREAD

**Issue by tilltonystark** [saving-satoshi/saving-satoshi#381]
![image](https://user-images.githubusercontent.com/89836460/231850259-d0111310-1cd0-4145-9999-3f416df97f7e.png)

We could transform that message into a snack bar, allowing the user greater autonomy to access and remove it at their convenience.

![image](https://user-images.githubusercontent.com/89836460/231854173-eb8ec9ae-b62e-404f-8313-2f7c947318f7.png)

Open to suggestions and further changes

**Comment by ecurrencyhodler** [comment]
Hey Tony! Nice idea. I was initially thinking we will be removing that text area for v1 as we will no longer be in a demo state. But now that I think about it, we could keep it or use the snack bar to convey that Ch.1 and 2 are done while the rest is being in development.

But let's get some feedback from @GBKS on this as well. 

In the future, if you would like to propose a design improvement it would be good to leave comments directly in our [figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=0%3A1). This is where we can hash out a plan and then create an issue for dev's to implement.

But I'm going to leave this issue open for now!

**Comment by GBKS** [comment]
Thanks for sharing. A few thoughts:

- The option of hiding can be a nice-to-have. However, then the user cannot access the feedback form anymore. I'd rather keep it static for the time being (maybe make it smaller if it's the size that's the problem).
- The snack bar feels foreign to the interface and we don't use it anywhere else. What's your rationale for this specific UI element? Mostly that you can hide it? Or that it's visually in-your-face so that you see it before anything else?

Another approach altogether could be to have a dedicated page that shows the first time you start the experience with a friendly disclaimer and request for feedback that doesn't feel like a system message. Just a thought though, hope it's helpful.

**Comment by shaavan** [comment]
A snack bar sounds like an interesting idea. But it might not be the best considering the points Christoph mentioned in his comment.

> 1. However, then the user cannot access the feedback form anymore.
> 2. The snack bar feels foreign to the interface and we don't use it anywhere else.

@GBKS 

Thinking about the dedicated page, I think it can be a potentially good idea, but it also has similar problems as the snack bar:

1. Placing a dedicated page for a disclaimer and feedback request before the actual story feels too on-the-face to me.
2. It makes finding the link to the feedback form difficult because now the user has to open the dedicated page to find the feedback URL.

I have one small suggestion to make. Can we experiment with having a collapsible permanent text area? It is expanded on the first opening but can be collapsed with only "This is a demo" visible in the collapsed state.

**Comment by ecurrencyhodler** [comment]
Just one small nit. We shouldn't use the language "demo" as we'll be moving out of that in the next release.

**Comment by ecurrencyhodler** [comment]
Here is the new design. Will close this ticket because it will be addressed in #402 
![235108105-5cb35fc3-0257-4406-a25a-d4112bf3590d](https://user-images.githubusercontent.com/32662508/235194904-afd44254-920e-488e-8f59-78e8b78fd331.png)
