### ISSUE TITLE
Use common denomination for hashrate

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#420]
Its pretty common to use a denomination like TH/s for hashrate. Whenever we show a hashrate, we should use the appropriate denomination (e.g. H/s, KH/s, MH/s, GH/s, TH/s). We should create a file for this in the `utils` folder so it can be easily reused. It should take a `number` an argument and return a `string`.

**Comment by sabakhilji** [comment]
Can I work on it?

**Comment by ecurrencyhodler** [comment]
I think this issue pertains to challenge 2 and challenge 3. Currently challenge 3 is in the works with vinayak. Once he merges his pr, we can begin QA and see where we can address this issue specifically. Let's follow up on this then.

**Comment by ecurrencyhodler** [comment]
Hey Kevin. Circling back on this.

Right now we decided to show hashes in exponential form rather than TH/s. Reason for this is to visually show the scale to the user as they mine. 

However in Ch. 3, there will be the ability for the player to click on the exponents to either toggle or display the appropriate H/s, KH/s, MH/s, GH/s, TH/s denominations. 

I still think it'd be helpful to keep these in a util folder so we can easily reuse them in later chapters if needed in the UI. WDYT?

<img width="492" alt="Screenshot 2023-06-12 at 9 15 14 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/08e39fa8-3d7d-4e6e-a6d8-a3eb124dc7eb">

**Comment by afterburn** [comment]
Yeah, I'm not sure we have any code right now that converts between the different units so we can add it later if we ever need it. Closing this for now.
