### ISSUE TITLE
Various UX Challenges for Ch.2 Challenge 1 & 2

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#427]
I did a quick run through of some of the challenges and am leaving some thoughts from a UX perspective of a player who is inexperienced with coding. I'm opening up this issue to start a discussion. Depending on how it goes, I may split this into individual issues. But let's discuss below.

**Ch.2 Challenge 1 Hashing-2**
url: en/chapters/chapter-2/hashing-2

It's not clear to me as a player what the success metric is to move on to the next section. It's not finding a hash with a "0". That's in pt. 2. To solve this, maybe we can say in the success bar at the bottom: "Nicely done! Now that you see how hashes work, continue to learn more about hashing!"

<img width="1099" alt="Screenshot 2023-05-05 at 12 45 31 PM" src="https://user-images.githubusercontent.com/32662508/236558345-d44e554c-bc7b-4446-80bd-d920c7976562.png">

**Ch.2 Challenge 1 Hashing-6**
en/chapters/chapter-2/hashing-6

It took a while to see "need a hint". This should appear faster. Also the word "trigonometry" is hidden. IMO it shouldn't because it's already hidden behind a tool tip. Lastly, I suggest copy changes from "Answer" to "Try typing: trigonometry"
<img width="1115" alt="Screenshot 2023-05-05 at 1 12 15 PM" src="https://user-images.githubusercontent.com/32662508/236561169-ec43c943-51f7-4df1-9cee-071559ae3466.png">

**Ch.2 Challenge 2 Hashing-6**
url: en/chapters/chapter-2/scripting-1

There is a copy mistake. Computem->computer
<img width="1112" alt="Screenshot 2023-05-05 at 12 46 45 PM" src="https://user-images.githubusercontent.com/32662508/236560625-bf0bca1e-a623-4ad2-a950-edae7e60327b.png">

**Ch.2 Challenge 2 Scripting-2**
url: en/chapters/chapter-2/scripting-2

I don't know if this is because I don't know how to code. But I got stuck on this challenge section because I didn't know what formula to write. Considering how in Ch. 1 we hand held people through decoding op_returns, should we do something similar for this challenge? Perhaps we can add a tooltip with the formula if people don't know how to start?
<img width="1109" alt="Screenshot 2023-05-05 at 12 48 24 PM" src="https://user-images.githubusercontent.com/32662508/236561007-c2028baa-48c4-4619-af3e-580c82dec44c.png">

**Comment by sabakhilji** [comment]
I have same thoughts for Ch.2 Challenge 2 Scripting-2. I think including a hint as in the other challenges will help here @ecurrencyhodler.

**Comment by GBKS** [comment]
Thanks for testing everything, that's exactly what we need to do. 

- For Ch.2 Challenge 1 Hashing-2, the copy in the design reads `Alright, nice work playing around. Let’s move on.`, it  (or something similar) just needs to be implemented (let's do that).
- I agree that the extra hover in the tool tip is unnecessary. The word `answer` is also a little misleading as there is not a single answer. `"Try typing: trigonometry"` sounds good. There also seems to be a visual glitch with the tooltip (arrow has no background color).
- For Ch.2 Challenge 2 Scripting-2, I also don't know what the answer should be. That is where the dev crew is best situated to provide some possible answers that users are likely to enter. Once we have that, we can figure out how to provide tips for non-coders (like me) to also succeed.

**Comment by satsie** [comment]
I agree with Christoph's reply. 

For the last one, Ch.2 Challenge 2 Scripting-2 I think at minimum we need to mention that the `sha256` function that is being imported generates a hash, perhaps even showing a one line example of how this library is used (I haven't taken a look a the latest wireframes so apologies if I'm repeating something that is already there). The only downside to this is we'd have to repeat this helper text for JavaScript.

From there I would expect the user to know how to write an if statement that checks if the resulting hash has 5 leading zeros. We should be careful about how much handholding we do, because every time we do it, it's expected that the same amount of assistance will be provided in the next chapter. 

As some of the feedback showed, we have users that are so advanced they are breaking our terminal, expecting it to do things a real terminal would. Yet on the other end of the spectrum, we have some users that felt like we didn't do enough coding explanations or hand holding. At some point we're going to need to really double down on who the target user is. My preference would be to cater to a more advanced audience because it requires less work, then slowly layer in more help text, tool tips, examples, and general suggestions as feedback comes in. This way, accommodating to a more beginner audience becomes an iterative process.

**Comment by ecurrencyhodler** [comment]
Okay so let's do this:

- [ ] Ch.2 Challenge 1 Hashing-2: Change success message to `Alright, nice work playing around. Let’s move on.`
- [ ] Ch.2 Challenge 1 Hashing-6: Update copy to "Try typing: trigonometry" and remove the hover functionality
- [ ] Ch.2 Challenge 2 Hashing-6: Update copy from computem -> computer
- [ ] Ch.2 Challenge 2 Scripting-2: Let's discuss this on our call. Will probably file a separate issue for this.

FWIW this is the answer in python:

from hashlib import sha256

def find_hash(nonce):
  hash = sha256(str(nonce).encode('utf-8')).hexdigest()

  return hash

**Comment by ecurrencyhodler** [comment]
The proposed solution here is to update the challenge copy slightly and to leave references to the sha256 library.

If someone gets stuck, we assume they'll google/stackexchange the solution which should be easy to find. This is also the behavior many devs take anyways when trying to figure out problems.

@benalleng will propose copy in figma. We'll use this issue to track whether it's been resolved.

**Comment by benalleng** [comment]
![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/5d7b0ab7-16bd-4c63-aad3-5960f48f084c)


[Figma](https://www.figma.com/file/vH59Zd9adCeFCJizEzVSoX/Saving-Satoshi-(Copy)?type=design&node-id=3101-30787&t=xXxkYUwGSA76lwTs-0)

**Comment by benalleng** [comment]
[Here](https://datagy.io/python-sha256/) is the resource i found to be the closest to our desired input

**Comment by ecurrencyhodler** [comment]
I can't speak to the resources. Left a comment in figma wrt to copy.

**Comment by GBKS** [comment]
Great updates, @benalleng. I managed to solve the challenge with this code:

`return crypto.createHash('sha256').update(nonce).digest('base64');`

The given [JS resource](https://www.geeksforgeeks.org/node-js-crypto-createhash-method/) was not helpful enough and I had to search further. [Here's the one](https://www.educative.io/answers/what-is-node-cryptocreatehashalgorithm-options) that led me to the correct solution.

Specifically, the `crypto.createHash()` function description only discusses the algorithm and options arguments. I could not figure out how to make it use the nonce. The page states there a Hash object is returned, but there is no further documentation on that object. Since that thing is called Hash, I thought this would be a text string and the correct output I need. Only via the second page did I understand that I need to chain multiple functions together.

Maybe a good approach is to have two types of links? One to the documentation for people who just need a bit more detail. And a second one to a tutorial that guides readers towards the solution.

**Comment by sabakhilji** [comment]
@GBKS well described article!! 
Giving options to the user will be a better UX approach I guess. 
The second article is really very helpful and it will drive the user to the exact solution.

**Comment by benalleng** [comment]
I have created a draft that doesn't use any dynamic copy. I'm curious to see what people think
![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/ad16b7b6-b15e-4fcc-bbe2-bc946112026c)

**Comment by benalleng** [comment]
And the dynamic code...
![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/de8feae7-1ffc-434d-b7ba-dd8f10fa4c60)
