### ISSUE TITLE
Screen persists after entering in my own secret to save progress 

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#525]
The screen persists after entering in my own secret to save my progress. 

But the good news is that I tried logging in using the secret I entered before and it does get saved to our database and my progress does get saved.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/3ec75329-0a96-4fe4-9ee1-c2ccecc05adb

**Comment by ecurrencyhodler** [comment]
@benalleng do you think you can pick up a component issue instead? I want to make sure we hit our 2 week deadline (6/27).

**Comment by benalleng** [comment]
The video specifically is because of an error not being shown, all privateKeys must be of a standard length `64` in our backend. this error is not being shown but that is the reason for the failure. based on our discussion in slack i think the best way to solve this is to remove the enter my own option

**Comment by ecurrencyhodler** [comment]
Concept ack on removing their own option.
