### ISSUE TITLE
Update Ch.3 Challenge 2 with HoloCat Pool. Also change names of Challenges 2 and 3.

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#619]
**UPDATE**
Here's what we need for this issue:

- [ ] Change name of Challenge 2 to Pool vs. BitRey (including URL, challenge copy, and chapter titles)
- [ ] Change name of Challenge 3 to Coop vs. BitRey (including URL, challenge copy, and chapter titles)
- [ ] We also need to need to add a frame around the cooperators in Challenge 2. But we won't be adding badges yet. Bades will only come into play for Challenge 3.

So this is challenge 2 right now.
<img width="1207" alt="Screenshot 2023-09-04 at 8 28 27 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/e22d6b37-fb1e-435b-9726-64ab1d71f2f4">

Challenge 2 will need the right side updated to the below image:
![265672139-f24eed4b-d29d-49fb-aabd-0d622196e1f6](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/bd48909b-d824-4d04-85eb-f6045f72776c)

**Comment by GBKS** [comment]
Re-reading the copy, I think there's a bit of a mix-up now due to some text changes.

The original idea was that we don't have a pool yet in "Coop vs BitRey". So everyone mines on their own. Then we form a pool in "Pool vs BitRey" and the badges appear. The copy was changed so that "Coop vs BitRey" already talks about a pool. See this screenshot from Figma and compare the copy on the left and right.

<img width="1199" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/79c90299-98ab-4fb6-966c-db807f882832">

I think it's more effective when the pool is only formed in "Pool vs BitRey", so there's a clear distinction between "everyone acting on their own" and properly collaborating.

If we want to go with the copy on the left (not what I'm recommending), then we also need to show the pool title and badges in "Coop vs BitRey".

Hope that all makes sense...

**Comment by ecurrencyhodler** [comment]
Ah I see. Okay. 

I think we need to add the badges in Coop vs Bitrey too then. That will be the simplest fix. 

So this is chapter-3/coop-1 right now.
<img width="1207" alt="Screenshot 2023-09-04 at 8 28 27 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/e22d6b37-fb1e-435b-9726-64ab1d71f2f4">


Chapter-3/coop-1 will need the right side updated.
<img width="624" alt="Screenshot 2023-09-04 at 8 28 17 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/87369082-bf22-4e14-9ce5-e5c8e036ba47">

I'll update the issue. Thanks.

**Comment by GBKS** [comment]
Sorry, I don't think that works too well without tweaks. One issue is that the naming is not that accurate anymore. If there is a pool already in "Coop vs BitRey", then the name "Pool vs BitRey" is not that great anymore.

Personally, I'd revert to the prior version. I don't think it's that much work.

If we go with what you suggest, I'd suggest a middle state for "Coop vs BitRey" where we indicate the pool, but not the identifiers, like this:

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/f24eed4b-d29d-49fb-aabd-0d622196e1f6)

Then we add the identifiers in "Pool vs BitRey".

**Comment by ecurrencyhodler** [comment]
Hmmm okay. Well right now the challenge for the coop vs bitrey is structured in such a way that:
1. Cooperators join the pool
2. But they don't split the nonce
3. Only 1 cooperator wins blocks because of this

This is why in the following scene all the hashers (outside of hash hoppers) have 0 blocks found. Because the only person who is finding blocks are the hashhoppers. Here is the PR for reference: https://github.com/saving-satoshi/saving-satoshi/issues/585#issue-1826283371

"The original idea was that we don't have a pool yet in "Coop vs BitRey". So everyone mines on their own." I'm actually not 100% sure how this idea would work in the real world without joining a pool of some sort. I feel like we may have similar ideas but are getting caught up on the semantics of "pool?"  I'm not sure. 

But I like the suggestion that you proposed in your last comment.

**Comment by ecurrencyhodler** [comment]
Okay I've updated the issue with Christoph's and Matthew's feedback. 
<img width="350" alt="Screenshot 2023-09-06 at 8 41 54 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/0b11bb0e-c65d-4512-b69c-afcf90a07437">
