### ISSUE TITLE
Prevent avatars in mining progress bar from being cut off

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#632]
Here's an example:

<img width="125" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/abe39ff0-eecd-4465-b102-987815f83126">

[Dev site link](https://dev.savingsatoshi.com/en/chapters/chapter-3/coop-2?dev=true).

**Comment by ecurrencyhodler** [comment]
Hey Christoph. Do you think it is necessary to see the avatars? I don't think it's too big of a concern/issue. I actually think it makes sense for them to overlap.

The problem is that these miners are finding 0 blocks and therefore we would have to adjust how the avatars are being displayed. 

Reason I ask is because we've tackled this section a couple of times already and would rather not try to tackle it again:
https://github.com/saving-satoshi/saving-satoshi/pull/608
https://github.com/saving-satoshi/saving-satoshi/pull/586

**Comment by GBKS** [comment]
I just mean that the edge of the bar cuts off the avatar circle. Overlap is fine.

**Comment by ecurrencyhodler** [comment]
tACK. Profiles are no longer cut off.
<img width="992" alt="Screenshot 2023-09-26 at 10 30 00 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/78012b68-3a76-4271-b7b2-a1ff9e594580">
