### ISSUE TITLE
Investigation: Embed repl.it

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#74]
We'd like to explore the possibility of using repl.it and need to investigate more. For this ticket, let's try embedding a REPL into this code base: https://docs.replit.com/hosting/embedding-repls

Here's a sample replit that can be used: https://replit.com/@satsie/Saving-Satoshi-Chapter-3-Challenge-2#main.py

Some questions a proof of concept would help answer:

- What does a REPL look and feel like when in the site?
- Do we have control over styling?
- Does it feel natural or alien in the context of our other challenges and UI design?
- Does it work on mobile?

Note that they also have an API so if we can't control the styling, we can still use the engine.

**Comment by aureleoules** [comment]
Apparently, we cannot use embeds anymore https://blog.replit.com/embeds-are-going-away. They are now read-only.

Though Replit provides an API to execute arbitrary code but requires a private token and no UI is provided.
We would have to execute these API requests server-side instead of client-side as to not leak our private token, maybe Next can handle this but I'm not familiar with it.
See https://github.com/replit/crosis.

So to answer @satsie's questions:
> What does a REPL look and feel like when in the site?
> Do we have control over styling?
> Does it feel natural or alien in the context of our other challenges and UI design?

We have full control.

> Does it work on mobile?

Yes.

I'm going to build a proof of concept to see how it works in depth.
We will need to refactor our Terminal component to be able to edit a file instead of just writing commands, or do that in a separate component.

**Comment by satsie** [comment]
Thank you for starting this investigation Aurèle! 

For posterity, I am leaving a note for something Jonas said in the chat: if we need to try and get support from Repl.it, let's wait until we have a more polished demo.

I don't think that should block you from the proof of concept work you are doing though, and look forward to seeing what else you find!

**Comment by ecurrencyhodler** [comment]
Due to time constraints, aureleoules won't be able to investigate or work on a proof of concept. This issue is still available for someone to help explore embedding repl.it.

**Comment by afterburn** [comment]
Happy to pick this up if there are no other volunteers

**Comment by ecurrencyhodler** [comment]
That would be greatly appreciated! Thanks afterburn.

**Comment by afterburn** [comment]
Posting my message from Slack here:

I've been in contact with someone from repl.it and it turns out both the API and Embeds were deprecated to funnel more users into their relatively new Teams products, which is maybe a smart move to make for their business but it's sad for us. Perhaps that connection @adamjonas mentioned earlier can hook us up with a custom solution, but I also feel we should wait a little longer until Saving Satoshi is more polished before we do that.

Alternatively we could look into other solutions, but I'm afraid (from what I've seen so far) there aren't any that are as good as [repl.it](http://repl.it/).

Some other thoughts that crossed my mind:
- If the goal is to only support js and python we could use [CodeMirror](https://codemirror.net/) as our front-end code editor, eval js code on the client, and create a backend service for running python code in a sandbox (and maybe other languages later on). This adds a ton of complexity though (and cost) so better if we can avoid it.
- Another less costly option is to use WebAssembly to run python code in the browser (and potentially other languages). But this is guaranteed to be a lot of work if we build it ourselves. There is a demo [here](https://python-browser-editor.onrender.com/).
- We could perhaps also simply fake it. We could pretend to run python (or other languages) while in actuality we just do some basic parsing and then do string comparisons in JS to determine correctness of the users code. Whenever the users input does not match the expected input we simply log that their code is invalid or something similar.

**Comment by ecurrencyhodler** [comment]
Vinayak found a docker image in a code sandbox. He is going to try to create an API so we can leverage it. We will have to host it ourselves.
https://github.com/saving-satoshi/code-sandbox

**Comment by satsie** [comment]
I think the WebAssembly example that Kevin shared is probably more recent, but here is another for reference: https://boot.dev/playground/py

**Comment by ecurrencyhodler** [comment]
We've determined replit won't be a viable solution for us. We will create our own docker container.
