### ISSUE TITLE
Remove mdx files and structure routes better

### ISSUE THREAD

**Issue by aureleoules** [saving-satoshi/saving-satoshi#79]
Currently, we have mdx files that contain the content of the lessons and some react code that displays them.
For each lesson, we seem to have lesson-specific react code so having mdx files is a bit redundant and it makes it difficult to add interactivity with lesson content (such as tooltips).
I think we should move away from mdx files and write the lesson content directly in the react code.

Also, we should remove the `[slug]` path and structure better the routes for chapters and lessons.
Currently, we have for chapter-1:  `/genesis`, `/genesis/genesis-pt2`, `/transacting-1` and `transaction-2`. This is not consistent.

**Comment by adamjonas** [comment]
Can you explain how you see this furthering https://github.com/saving-satoshi/saving-satoshi/issues/3#issue-1432017582? Keeping the content independent from the platform seems like the easiest way to allow for content updates without people needing to understand the code.

**Comment by aureleoules** [comment]
You are right it would be nice to keep the content separated from the code as it would allow contributors to easily add challenges. But in practice, it seems that each challenge requires its own rendering and challenge validation code. So even if we keep the content out of the react, some code will still need to be written.
 
We could (we should) wrap some lessons into reusable components such as the terminal-based one as they always have the same UI, and always expect certain user input. Same for chapter 1 - challenge 1 where you have to paste the scriptSigHex, it can be a reusable component.
Contributors could then more easily use this challenge template. With this PR, it should only require adding the challenge to the `chapters.json` file and creating a page in a folder with the reusable challenge react component and passing a few props. With clear documentation, it shouldn't be too hard.
And if they wish to add a challenge that is more complex, they can write the code for it.

**Comment by adamjonas** [comment]
I'm not adamant about keeping current setup and at this point, I think we should be optimizing of the creation of the product rather than the mythical future content/storyline contribution, but what I really like about this initial design was a clear delineation of the words and the platform.

If we are going to go with #80 then I'd like to clearly map out a future where content contributors can easily contribute to the project. Ideally this would be a different repo like how [exercism](https://github.com/exercism) or [cryptozombies](https://github.com/CryptozombiesHQ/cryptozombies-lesson-code) does it.

**Comment by GBKS** [comment]
Lots of architecting to do to achieve this, especially if we also want to support i18n.

I could imagine that we have some templated lessons and some super unique lessons in the future (like mining). The former would work like @aureleoules described. Maybe you just need to provide a JSON file with the template name, configuration, etc. Public contribution would be easier there. The latter would require more custom code, but could still support i18n, and would be more like a small project.

One thing is am pretty sure of is that the use of simple markdown files is not enough. It works for chapter intro pages that just contain text and a button, and maybe for the most basic lesson. But beyond that it's not flexible enough.

Maybe best to keep this an eye on this problem and gather requirements and think of solutions until we're a bit further in?

**Comment by afterburn** [comment]
Hi there, I think its a must to move away from `.mdx` files if the plan is to let contributors add **any** complex challenges at all somewhere in the future (like the mining example from the previous comment). From what I've gathered from both this ongoing conversation (and from some comments in the code) the biggest concerns with moving to React code away from mdx are:
1. The added complexity / extra boilerplate that future contributors will have to write, and
2. The loss of separation between lesson content and platform code.

I would like to propose the following solution:

1. We create a component library consisting of elements that make up the bulk of lesson content (think `Heading`, `Text`, `Inputs`, `Terminal`, etc) and publish this as a npm package. Lets call it `@savingsatoshi/ui` for now. This will allow us to move lessons (and other materials) away from this repo and into another repo I'll call `@savingsatoshi/lessons`, similar to how cryptozombies does it. The added benefit of this component library is that we'll have full control over how the components are styled instead of contributors being able to introduce their own components and styling.
2. Lessons (and other materials) can be created as `.tsx` files (for cryptozombies they are `.sol`) and will be pushed to the `@savingsatoshi/lessons` repo which will also be published as npm package. Within this repo Curriculum Contributors can simply import the `@savingsatoshi/ui` library and create their lesson. The following examples demonstrate both a simple and "complex" lesson:

```jsx
// Simple.tsx
import { Heading, Text } from '@savingsatoshi/ui'

export default () => (
  <>
    <Heading>Find block 0</Heading>

    <Text>
      Let's find the very first block in the Bitcoin blockchain. Go to a block
      explorer and search for '0'. This will take you to the block at height 0.
      As you can see, this block only contains one transaction.
    </Text>

    <Text>
      Open up the transaction so you can take a closer look at the details. On
      the left is an input called 'Coinbase'. Inside that is a field called
      'ScriptSig'. Find the HEX representation and paste it below.
    </Text>
  </>
);

```

```jsx
// Complex.tsx
import { Heading, Text, IndividualCharacterInput } from '@savingsatoshi/ui'

export default function Genesis() {
  const [userInput, setUserInput] = useState('');

  // Room for any complex logic contributors can come up with.

  return (
    <>
      <Heading>Find block 0</Heading>

      <Text>
        Let's find the very first block in the Bitcoin blockchain. Go to a block
        explorer and search for '0'. This will take you to the block at height
        0. As you can see, this block only contains one transaction.
      </Text>

      <Text>
        Open up the transaction so you can take a closer look at the details. On
        the left is an input called 'Coinbase'. Inside that is a field called
        'ScriptSig'. Find the HEX representation and paste it below.
      </Text>

      <IndividualCharacterInput
        value={userInput}
        onChange={(val) => setUserInput(val)}
      />
    </>
  );
}
```
3. On the platform repo (this one probably) we simply import `@savingsatoshi/lessons` and render out the lessons.

This solution first and foremost enforces the separation between lesson content and the code that runs it, thereby making sure that contributors aren't overwhelmed with the codebase. At the same time, it also makes sure the Curriculum Contributors do not have to write a ton of boilerplate code to get their lesson up and running. From the perspective of a Curriculum Contributor it is a very simple process to add content.

**Comment by 0xBEEFCAF3** [comment]
Hi! I Agree with the solution laid out above. You can also create layout components for recurring pages. For example, each chapter could have a similar intro page format.

```js
// ChapterIntro.tsx
import { Heading, SubHeading, Text, IndividualCharacterInput } from '@savingsatoshi/ui'
const ChapterIntro = ({title, subTitle, body}) =>{
    return(
        <div style={introPageStyling}>
            <Heading>{title}</Heading>
            <SubHeading>{subTitle}<SubHeading />
            <Text>{body}</Text>
        </div>
    )
}
```

As for internationalization, I have had good experiences with [formatjs](https://formatjs.io/). I recommend building a set of wrapper hooks. For example, useTranslate(), useDate(), useNumbers(), etc... And maintain a set of key-value mappings in a separate directory, say @savingsatoshi/translations. 
So for example, 
```js 
// @savingsatoshi/translations/en-US.ts
export const translation = {
  my_key: 'Hello, {name}!',
}

// Any component
function MyTranslatedComponent() {
  const { translate } = useTranslate()
  return <div>{translate('my_key', { name: 'Satoshi' })}</div>
}

```
Keys in `@savingsatoshi/translations/*.ts` can be broken down by lesson and chapter.
This approach would add an additional step to contributing lesson material. But nothing that can't be explained in `CONTRIBUTING.MD`.

**Comment by GBKS** [comment]
One thing I'd ask for in this discussion is to base the technical solution on our desired experience. For example, I'd rather not prescribe a strict content structure (title, sub-title, paragraph) on every chapter intro page. Similarly, interactive coding experiences can really benefit if the challenges have some unique touches. For example, if we realize that most learners make a specific mistake in a challenge, it would be great to have a unique response and a tip just on that page. The balance between standardization and customization is very important.

As for making it easy for content contributors, I think we will have some minimal required technical knowledge anyways, simply because people who create technical learning material for bitcoin will automatically have a certain understanding. But naturally we need to make it as simple as we can. Something that has worked well so far was that lessons start in a Google Doc or Notion, then go through design and only later get ported into code once things are fairly finalized. This is more accessible and moves and coding requirements to the end of the process.

For localization via JSON and Strings, is it possible to embed custom tool tips ([example](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1056%3A14226&t=DnuGCqA15aHudVsp-1)) and potentially other components?

Maybe it's a good idea to write down our requirements for this architecture (across tech, design, content...)? And then derive specs and solutions from those?

**Comment by afterburn** [comment]
Hi @GBKS, yes the example I gave with `<Heading>`, `<Text>`, was just that, an example. Contributors would be free to create their own components if they wanted to, I merely suggested we provide them some easy to use building blocks to get them started quicker. As for custom tooltips / other custom components; these should be no issue with the solution I proposed.

This solution also lends itself extremely well to translations like @0xBEEFCAF3 mentioned before, though I feel we'd probably need to establish some proper guidelines/conventions for how we define the translationos because I can see that becoming a mess fast without proper guidance.

**Comment by SamSamskies** [comment]
Hi, hope I'm not adding too many cooks to the kitchen on this issue, but have you thought about using a CMS like [Strapi](https://strapi.io/) for the content? Strapi would make it easy for anyone to contribute content and it would make it easy for the developers to consume the content via an API. It looks like it would be very easy to [add on i18n support](https://docs.strapi.io/user-docs/latest/content-manager/translating-content.html) as well. You wouldn't even need a client library for the localized copy. All the localized copy could be easily retrieved using the Strapi API.

Flow could be something like this:
1. Content creator submits lesson using Google Docs
2. Discuss lesson and make changes if necessary on the Google Doc
3. Assign someone to input the lesson into Strapi using the dashboard and publish (no coding or git knowledge necessary to do this)
4. Developers consume the data using the Strapi API using the component structure using the `@savingsatoshi/ui` components

I've never actually used Strapi, but I researched it a little and it seems like it would work well for this project. The Strapi free tier also looks like it would be sufficient. Only cost would be hosting which I think would only be $5 a month on DigitalOcean. Might be worth it for someone to do a spike on using it.

> Maybe best to keep this an eye on this problem and gather requirements and think of solutions until we're a bit further in?

Also, I agree with @GBKS that it would probably be better to punt on making the architectural changes right now. I'm new here, but it seems like more research and discussion needs to be done before making any architecture changes. 

> Maybe it's a good idea to write down our requirements for this architecture (across tech, design, content...)? And then derive specs and solutions from those?

+1 on that as well.

**Comment by ecurrencyhodler** [comment]
Just making a note (mostly for myself) that this has been assigned to afterburn after our call today as he is going to take a stab at it.

**Comment by ecurrencyhodler** [comment]
Moving this to "In Progress". Here is afterburn's spike: https://github.com/saving-satoshi/saving-satoshi/pull/118

**Comment by ecurrencyhodler** [comment]
Closing issue as PR has been merged!
