### ISSUE TITLE
upgrade favicon resolution

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#799]
<img width="48" alt="Screenshot 2023-12-11 at 10 28 00 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/755825/18530d4e-b378-4d7d-b4bc-42b47878de62">

The current favicon is pretty grainy.

**Comment by GBKS** [comment]
One issue I see here is that rendered HTML of the site does not list out all the needed favicon sizes that are needed. `head.tsx` lists them, but somehow that does not make it into the rendered HTML. So that would be first thing to fix, so browsers can choose from those higher-res images.

The second thing is that we should update the images themselves. I can put something together for that.
